export const MESSAGES = {
  LINK_CREATED: "Link generated successfully",
  LINK_NOT_FOUND: "Short link not found",
  CREATED: "User created successfully",
  LOGIN_SUCCESS: "Login successful",
  LOGOUT_SUCCESS: "Logged out successfully",
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXIST: "User already exist",
  USERS_FETCHED: "Users fetched successfully",
  PHONE_REQUIRED: "Phone number is required",
  MESSAGE_REQUIRED: "Message is required",
  MUST_BE_PRO: "You must become a premium user to generate a branded page link",
  OTP_SENDED: "OTP sent to your email successfully",
  OTP_SENDED_PASSWORD: "OTP sent to your email for password reset.",
  EMAIL_OTP_REQUIRED: "Email and OTP are required",
  INVALID_FORMAT: "Invalid email format",
  INVALID_CREDENTIALS: "Invalid email or password",
  INVALID_OTP: "The OTP provided is invalid",
  OTP_EXPIRED: "OTP has expired",
  PASSWORD_CHANGED: "Password has been reset successfully.",
  ACCOUNT_NOT_FOUND: "No account found with this email. Please sign up first.",
};